name: build-wasm
on: [workflow_call, workflow_dispatch]
jobs:
  build-wasm:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v13
        with:
          version: 3.1.58
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install Nightly Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Python packages
        run: pip install -r python/requirements.txt
      - name: Build wheel
        run: make build-wasm
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: pyxel-wasm
          path: dist/*